apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: flask-todo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-auto
  resources:
    requests:
      storage: 5Gi
